name: Get YouTube Video Info

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "YouTube Video URL"
        required: true

jobs:
  get_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      # (Optionnel) Recoller 10 secrets cookies en un seul fichier base64,
      # puis les décoder dans cookies.txt si tu utilises des cookies.
      - name: Recreate base64 cookie file from parts (optional)
        if: ${{ secrets.COOKIES_PART_01 != '' }}
        run: |
          mkdir -p .private
          for i in 01 02 03 04 05 06 07 08 09 10; do
            part="COOKIES_PART_${i}"
            val="${{ secrets[format('COOKIES_PART_{0}', i)] }}"
            if [ -n "$val" ]; then echo "$val" >> .private/cookie.txt.base64; fi
          done

      - name: Decode cookies.txt (optional)
        if: ${{ secrets.COOKIES_PART_01 != '' }}
        run: |
          base64 -d .private/cookie.txt.base64 > cookies.txt
          echo "COOKIES_FILE=$GITHUB_WORKSPACE/cookies.txt" >> $GITHUB_ENV

      - name: Prepare output filename
        id: prep
        run: |
          url="${{ github.event.inputs.video_url }}"
          slug=$(echo "$url" | sed 's/[^a-zA-Z0-9]/_/g')
          ts=$(date +%s)
          mkdir -p outputs
          echo "filename=outputs/output_${slug}_${ts}.json" >> "$GITHUB_OUTPUT"

      # Petit debug pour vérifier que le dossier existe bien
      - name: Debug outputs folder
        run: |
          echo "Listing repository root:"
          ls -la
          echo "Listing outputs/:"
          ls -la outputs || true

      - name: Run extractor (main.py)
        env:
          COOKIES_FILE: ${{ env.COOKIES_FILE }}
        run: |
          python main.py "${{ github.event.inputs.video_url }}" "${{ steps.prep.outputs.filename }}"

      # Re-debug après génération
      - name: Check generated file
        run: |
          echo "Expecting file: ${{ steps.prep.outputs.filename }}"
          test -f "${{ steps.prep.outputs.filename }}" && echo "OK: file exists" || (echo "ERROR: file not found" && exit 1)
          head -n 40 "${{ steps.prep.outputs.filename }}"

      - name: Commit result JSON
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "${{ steps.prep.outputs.filename }}" || true
          git commit -m "Add video info: ${{ steps.prep.outputs.filename }}" || echo "Nothing to commit"
          git push "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git" HEAD:main
