name: Get YouTube Video Info

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube Video URL'
        required: true

jobs:
  get_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp requests

      # Optionnel: si tu ajoutes un secret COOKIES_B64, on l'écrit en cookies.txt
      - name: Prepare cookies (optional)
        if: ${{ env.COOKIES_B64 != '' || secrets.COOKIES_B64 != '' }}
        env:
          COOKIES_B64: ${{ secrets.COOKIES_B64 }}
        run: |
          echo "${COOKIES_B64}" | base64 -d > cookies.txt

      - name: Prepare output filename
        id: prep
        env:
          VIDEO_URL: ${{ github.event.inputs.video_url }}
        run: |
          slug="$(echo "$VIDEO_URL" | sed 's/[^a-zA-Z0-9]/_/g')"
          ts="$(date +%s)"
          mkdir -p outputs
          echo "FILENAME=outputs/output_${slug}_${ts}.json" >> $GITHUB_ENV
          echo "filename=outputs/output_${slug}_${ts}.json" >> $GITHUB_OUTPUT

      - name: Run extractor (with cookies if present)
        env:
          VIDEO_URL: ${{ github.event.inputs.video_url }}
        run: |
          if [ -f cookies.txt ]; then
            python main.py "$VIDEO_URL" "${FILENAME}"
          else
            python main.py "$VIDEO_URL" "${FILENAME}"
          fi

      - name: Commit result JSON
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "${FILENAME}"
          git commit -m "Add video info: ${FILENAME}" || echo "No changes to commit"
          git push "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git" HEAD:main
