name: Scrape YouTube Channel

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "URL de la vidéo YouTube"
        required: true
        type: string

jobs:
  get-video-info:
    runs-on: ubuntu-latest

    env:
      COOKIES_PART_01: ${{ secrets.COOKIES_PART_01 }}
      COOKIES_PART_02: ${{ secrets.COOKIES_PART_02 }}
      COOKIES_PART_03: ${{ secrets.COOKIES_PART_03 }}
      COOKIES_PART_04: ${{ secrets.COOKIES_PART_04 }}
      COOKIES_PART_05: ${{ secrets.COOKIES_PART_05 }}
      COOKIES_PART_06: ${{ secrets.COOKIES_PART_06 }}
      COOKIES_PART_07: ${{ secrets.COOKIES_PART_07 }}
      COOKIES_PART_08: ${{ secrets.COOKIES_PART_08 }}
      COOKIES_PART_09: ${{ secrets.COOKIES_PART_09 }}
      COOKIES_PART_10: ${{ secrets.COOKIES_PART_10 }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || pip install yt-dlp

      - name: Prepare output filename
        id: prep
        run: |
          slug=$(echo "${{ github.event.inputs.video_url }}" | sed 's/[^a-zA-Z0-9]/_/g')
          ts=$(date +%s)
          mkdir -p outputs
          echo "filename=outputs/output_${slug}_${ts}.json" >> "$GITHUB_OUTPUT"

      - name: Debug outputs folder
        run: |
          echo "Listing outputs folder:"
          ls -la outputs || true

      - name: Run extractor
        run: |
          echo "Running main.py with video: ${{ github.event.inputs.video_url }}"
          python main.py "${{ github.event.inputs.video_url }}" "outputs/${{ steps.prep.outputs.filename }}"

      - name: Re-debug after generation
        run: |
          echo "Expecting file: ${{ steps.prep.outputs.filename }}"
          ls -la outputs || true
          test -f "${{ steps.prep.outputs.filename }}" && echo "✅ File exists" || echo "❌ File missing"

      - name: Commit result JSON
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "${{ steps.prep.outputs.filename }}" || true
          git commit -m "Add video info: ${{ steps.prep.outputs.filename }}" || echo "Nothing to commit"
          git push "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git" HEAD:main || echo "Push skipped"
